// Static comic book data
const comicsData = [
    {
        id: '001',
        title: 'Amazing Spider-Man #800',
        character: 'Spider-Man',
        publisher: 'Marvel',
        genre: 'Superhero',
        price: 29.99,
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        description: 'The landmark 800th issue! Peter Parker faces his greatest challenge yet as the Red Goblin strikes with devastating force. Dan Slott delivers an epic conclusion to his legendary run with jaw-dropping action and heart-wrenching drama that will change Spider-Man forever.',
        writer: 'Dan Slott',
        artist: 'Stuart Immonen',
        releaseDate: '2024-05-15',
        featured: true,
        popular: true
    },
    {
        id: '002',
        title: 'Spider-Man: Miles Morales #1',
        character: 'Spider-Man',
        publisher: 'Marvel',
        genre: 'Superhero',
        price: 24.99,
        image: 'https://images.unsplash.com/photo-1608889476561-6242cfdbf622?w=400&h=600&fit=crop',
        description: 'Miles Morales swings into a brand-new adventure! Balancing his life as a student, a son, and a Super Hero, Miles discovers a mysterious new threat emerging in Brooklyn. With his unique spider-powers and unwavering courage, Miles must prove he has what it takes to be the ultimate Spider-Man.',
        writer: 'Saladin Ahmed',
        artist: 'Carmen Carnero',
        releaseDate: '2024-06-20',
        featured: true,
        popular: false
    },
    {
        id: '003',
        title: 'Batman: The Dark Knight Returns',
        character: 'Batman',
        publisher: 'DC',
        genre: 'Action',
        price: 34.99,
        image: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=400&h=600&fit=crop',
        description: 'Frank Miller\'s masterpiece redefined Batman for a generation. In a dystopian future, an aging Bruce Wayne emerges from retirement to reclaim Gotham City from chaos. This groundbreaking story explores themes of aging, redemption, and the enduring power of heroism in a dark and unforgiving world.',
        writer: 'Frank Miller',
        artist: 'Frank Miller',
        releaseDate: '2024-03-10',
        featured: false,
        popular: true
    },
    {
        id: '004',
        title: 'Superman: Action Comics #1000',
        character: 'Superman',
        publisher: 'DC',
        genre: 'Superhero',
        price: 39.99,
        image: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=400&h=600&fit=crop',
        description: 'Celebrate 80 years of the Man of Steel in this historic milestone issue! An all-star lineup of legendary creators pays tribute to Superman with unforgettable stories that showcase why he remains the world\'s greatest superhero. From his earliest adventures to modern-day heroics, this is a must-have for any fan.',
        writer: 'Brian Michael Bendis',
        artist: 'Jim Lee',
        releaseDate: '2024-04-18',
        featured: true,
        popular: true
    },
    {
        id: '005',
        title: 'Iron Man #500',
        character: 'Iron Man',
        publisher: 'Marvel',
        genre: 'Sci-Fi',
        price: 27.99,
        image: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=400&h=600&fit=crop',
        description: 'Tony Stark pushes the boundaries of technology and heroism in this explosive milestone! When a dangerous new threat emerges from the depths of space, Iron Man must utilize every ounce of his genius to save Earth. Featuring stunning armor designs and explosive action that will leave you breathless.',
        writer: 'Matt Fraction',
        artist: 'Salvador Larroca',
        releaseDate: '2024-07-01',
        featured: false,
        popular: true
    },
    {
        id: '006',
        title: 'Wonder Woman: Year One',
        character: 'Wonder Woman',
        publisher: 'DC',
        genre: 'Adventure',
        price: 26.99,
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        description: 'Discover the origin of DC\'s greatest warrior! Diana of Themyscira leaves her island home for the first time to bring peace to a world torn by conflict. Greg Rucka and Nicola Scott craft a powerful tale of heroism, sacrifice, and the true meaning of being a champion for justice.',
        writer: 'Greg Rucka',
        artist: 'Nicola Scott',
        releaseDate: '2024-08-12',
        featured: true,
        popular: false
    },
    {
        id: '007',
        title: 'The Amazing Spider-Man: Kraven\'s Last Hunt',
        character: 'Spider-Man',
        publisher: 'Marvel',
        genre: 'Action',
        price: 32.99,
        image: 'https://images.unsplash.com/photo-1608889825297-acf8d0d87e52?w=400&h=600&fit=crop',
        description: 'One of the greatest Spider-Man stories ever told! Kraven the Hunter finally captures his greatest prey, but his victory comes at a terrible price. This psychological thriller explores the darkest corners of obsession and identity, featuring some of the most haunting imagery in comic book history.',
        writer: 'J.M. DeMatteis',
        artist: 'Mike Zeck',
        releaseDate: '2024-02-25',
        featured: false,
        popular: true
    },
    {
        id: '008',
        title: 'Batman: Court of Owls',
        character: 'Batman',
        publisher: 'DC',
        genre: 'Superhero',
        price: 28.99,
        image: 'https://images.unsplash.com/photo-1601645191163-3fc0d5d64e35?w=400&h=600&fit=crop',
        description: 'Scott Snyder and Greg Capullo unveil a terrifying new threat to Gotham! The Court of Owls has controlled the city from the shadows for centuries, and now they\'ve set their sights on Batman. This modern classic features incredible twists, stunning artwork, and a labyrinth sequence you\'ll never forget.',
        writer: 'Scott Snyder',
        artist: 'Greg Capullo',
        releaseDate: '2024-09-30',
        featured: true,
        popular: true
    },
    {
        id: '009',
        title: 'Invincible #1',
        character: 'Invincible',
        publisher: 'Image',
        genre: 'Superhero',
        price: 22.99,
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        description: 'Robert Kirkman introduces the world to Mark Grayson! As the son of the world\'s most powerful superhero, Mark discovers his own incredible abilities. But being a teenage superhero is tougher than it looks, and the world is far more dangerous than he ever imagined.',
        writer: 'Robert Kirkman',
        artist: 'Cory Walker',
        releaseDate: '2024-01-15',
        featured: false,
        popular: false
    },
    {
        id: '010',
        title: 'Saga Vol. 1',
        character: 'Original',
        publisher: 'Image',
        genre: 'Sci-Fi',
        price: 31.99,
        image: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=400&h=600&fit=crop',
        description: 'Brian K. Vaughan and Fiona Staples create an epic space opera unlike anything you\'ve ever read! Two soldiers from opposite sides of a never-ending galactic war fall in love and risk everything to raise their daughter in peace. Featuring breathtaking artwork and unforgettable characters.',
        writer: 'Brian K. Vaughan',
        artist: 'Fiona Staples',
        releaseDate: '2024-10-08',
        featured: true,
        popular: true
    },
    {
        id: '011',
        title: 'The Walking Dead #1',
        character: 'Original',
        publisher: 'Image',
        genre: 'Action',
        price: 45.99,
        image: 'https://images.unsplash.com/photo-1608889476561-6242cfdbf622?w=400&h=600&fit=crop',
        description: 'The comic that started a phenomenon! Rick Grimes awakens from a coma to find the world overrun by zombies. This is the beginning of Robert Kirkman\'s groundbreaking series that redefined the zombie genre and became a cultural touchstone.',
        writer: 'Robert Kirkman',
        artist: 'Tony Moore',
        releaseDate: '2024-11-20',
        featured: false,
        popular: true
    },
    {
        id: '012',
        title: 'Spider-Verse',
        character: 'Spider-Man',
        publisher: 'Marvel',
        genre: 'Adventure',
        price: 35.99,
        image: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=400&h=600&fit=crop',
        description: 'Every Spider-Man from every universe is under attack! Peter Parker must unite with alternate versions of himself, including Spider-Gwen, Spider-Man 2099, and Spider-Ham, to stop a cosmic threat. This dimension-spanning epic changed everything we knew about the Spider-Man mythos.',
        writer: 'Dan Slott',
        artist: 'Olivier Coipel',
        releaseDate: '2024-12-05',
        featured: true,
        popular: false
    }
];
